// MEDICNE
export const SEARCH_MEDICINE = 'SEARCH_MEDICINE';
export const GET_RECENT_SEARCH = 'GET_RECENT_SEARCH';
export const GET_MEDICINE_CART = 'GET_MEDICINE_CART';
export const MEDICINE_CART = 'MEDICINE_CART';
export const MEDICINE_ADDED = 'MEDICINE_ADDED';
export const CLEAR_SEARCH_RESULT = 'CLEAR_SEARCH_RESULT';

// STORE
export const SEARCH_STORE = 'SEARCH_STORE';
export const CLEAR_STORE = 'CLEAR_STORE';
